default_events:
- check_run
- check_suite
- pull_request
default_permissions:
  checks: write
  metadata: read
name: In Solidarity
url: jpoehnelt.github.io/solidarity
description: Helping developers use racially neutral language.
public: false
