default_events:
- check_run
- check_suite
- pull_request
default_permissions:
  checks: write
  metadata: read
name: In Solidarity
url: https://github.com/jpoehnelt/in-solidarity-bot
description: Helping developers use inclusive language.
public: false
