steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
    - kms
    - decrypt
    - --ciphertext-file=key.pem.enc
    - --plaintext-file=key.pem
    - --location=global
    - --keyring=in-solidarity-bot
    - --key=github-app-key
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/in-solidarity-bot:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/in-solidarity-bot:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "in-solidarity-bot",
        "--image",
        "gcr.io/$PROJECT_ID/in-solidarity-bot:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--labels", 
        "sha=$COMMIT_SHA"
      ]
images:
  - gcr.io/$PROJECT_ID/in-solidarity-bot:$COMMIT_SHA