name: "Build"
on: 
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm i
        npm test
    - uses: codecov/codecov-action@v1
