# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - run: npm i
      - run: npm run build
      - run: npm run docs
      - run: npm run lint
      - run: npm test
      - run: docker build . --file Dockerfile
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            "@semantic-release/commit-analyzer"
            "@semantic-release/release-notes-generator"
            "@semantic-release/git"
            "@semantic-release/github"
            "@semantic-release/npm"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: Justin Poehnelt
          GIT_AUTHOR_EMAIL: 3392975+jpoehnelt@users.noreply.github.com
          GIT_COMMITTER_NAME: Justin Poehnelt
          GIT_COMMITTER_EMAIL: 3392975+jpoehnelt@users.noreply.github.com
          NPM_TOKEN: ${{ secrets.NPM_WOMBAT_TOKEN }}
